ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-favorites]]
== Favorite

[[resources-favorites-create]]
=== 즐겨찾기 추가

operation::favorites/create[snippets='http-request,http-response,request-headers,request-fields']

[[resources-favorites-findlist]]
=== 즐겨찾기 목록 조회

operation::favorites/find-list[snippets='http-request,http-response,request-headers,response-fields']

[[resources-favorites-delete]]
=== 즐겨찾기 제거

operation::favorites/delete[snippets='http-request,http-response,request-headers']


[[resources-paths]]
== paths

[[resources-paths-distance]]
=== 경로 조회(거리 기반)

operation::paths/distance/with-header[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-paths-duration]]
=== 경로 조회(시간 기반)

operation::paths/duration/with-header[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-paths-duration]]
=== 경로 조회(로그인 없이 시간 기반)

operation::paths/duration/without-header[snippets='http-request,http-response,request-headers,request-fields,response-fields']
